outputs:
  default:
    type: elasticsearch
    hosts:
      - "http://10.10.1.1:9200"
    username: "elastic"
    password: "vagrant"

inputs:
  - id: windows-sysmon
    type: logfile
    data_stream:
      namespace: default
    streams:
      - data_stream:
          type: logs
          dataset: windows.sysmon_operational
        paths:
          - C:\Windows\System32\winevt\Logs\Microsoft-Windows-Sysmon%4Operational.evtx
